FROM ruby:2.7.0-slim

ARG BUNDLER_VERSION
ENV BUNDLER_VERSION=${BUNDLER_VERSION:-2.1.4}

ENV RAILS_ENV production

RUN mkdir -p /app \
  && apt-get update -qq \
  && apt-get install -yq apt-utils build-essential libpq-dev postgresql-client git curl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log

WORKDIR /app

# Upgrade RubyGems and install required Bundler version
RUN gem update --system && \
  gem install bundler -v $BUNDLER_VERSION
